# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "contests", :force => true do |t|
    t.column "contest_name", :string
    t.column "created_at",   :datetime
  end

  create_table "game_scores", :force => true do |t|
    t.column "team_id", :integer
    t.column "game_id", :integer
    t.column "score",   :integer
  end

  add_index "game_scores", ["team_id"], :name => "fk_game_scores_teams"
  add_index "game_scores", ["game_id"], :name => "fk_game_scores_gane_id"

  create_table "games", :force => true do |t|
    t.column "contest_id", :integer
  end

  add_index "games", ["contest_id"], :name => "fk_games_contest_id"

  create_table "players", :force => true do |t|
    t.column "username", :string
    t.column "password", :string
    t.column "email",    :string
  end

  create_table "ratings", :force => true do |t|
    t.column "player_id",  :integer
    t.column "sport_id",   :integer
    t.column "rating",     :float
    t.column "created_at", :datetime
  end

  add_index "ratings", ["sport_id"], :name => "fk_ratings_sport_id"
  add_index "ratings", ["player_id"], :name => "fk_ratings_players"

  create_table "records", :force => true do |t|
    t.column "sport_id",  :integer
    t.column "player_id", :integer
    t.column "wins",      :integer
    t.column "losses",    :integer
  end

  add_index "records", ["sport_id"], :name => "fk_records_sport_id"
  add_index "records", ["player_id"], :name => "fk_records_players"

  create_table "sports", :force => true do |t|
    t.column "sport_name", :string
  end

  create_table "teams", :force => true do |t|
    t.column "team_name", :string
    t.column "player_id", :integer
  end

  add_index "teams", ["player_id"], :name => "fk_teams_players"

end
